### ISSUE TITLE
Not able to set bot token 

### ISSUE THREAD

**Issue by GauravM512** [nano-shino/genshinhelper#2]
Error:

~ $ cd ~/storage/downloads/genshin/src
~/.../genshin/src $ python main.py
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:logging in using static token
INFO:discord.client:Cleaning up tasks.
INFO:discord.client:Closing the event loop.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/http.py", line 406, in static_login
    data = await self.request(Route("GET", "/users/@me"))
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/http.py", line 359, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/emulated/0/Download/genshin/src/main.py", line 92, in <module>
    bot.run(conf.DISCORD_BOT_TOKEN)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/client.py", line 715, in run
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/client.py", line 694, in runner
    await self.start(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/client.py", line 657, in start
    await self.login(token)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/client.py", line 514, in login
    data = await self.http.static_login(token.strip())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/http.py", line 410, in static_login
    raise LoginFailure("Improper token has been passed.") from exc
discord.errors.LoginFailure: Improper token has been passed.
~/.../genshin/src $ python main.py
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:logging in using static token
INFO:discord.client:Cleaning up tasks.
INFO:discord.client:Closing the event loop.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/http.py", line 406, in static_login
    data = await self.request(Route("GET", "/users/@me"))
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/http.py", line 359, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/emulated/0/Download/genshin/src/main.py", line 92, in <module>
    bot.run(conf.DISCORD_BOT_TOKEN)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/client.py", line 715, in run
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/client.py", line 694, in runner
    await self.start(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/client.py", line 657, in start
    await self.login(token)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/client.py", line 514, in login
    data = await self.http.static_login(token.strip())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/http.py", line 410, in static_login
    raise LoginFailure("Improper token has been passed.") from exc
discord.errors.LoginFailure: Improper token has been passed.
~/.../genshin/src $

.env values :
LEVEL_1_GUILDS=
LEVEL_2_GUILDS=
LEVEL_3_GUILDS=
LEVEL_4_GUILDS=
LEVEL_5_GUILDS=
BOT_TOKEN='OTYxNjU4ODM2Mjc4NzEwMjgy.etc'
IMAGE_HOSTING_CHANNEL_ID=
ROUTE_CHANNEL_IDS=
NEWS_CHANNEL_IDS=
CODE_CHANNEL_IDS=

**Comment by nano-shino** [comment]
First, you should not post your bot token publicly.
Second, the bot doesn't accept quotation so you need to remove it (e.g. BOT_TOKEN=abc...xyz)

**Comment by GauravM512** [comment]
Can you help me setting my bot up?..

**Comment by nano-shino** [comment]
Sure. You can join https://discord.gg/HgTNWYBF for bot support.
I assume you have some Python and Discord bot knowledge? I can help answer some question but I won't hold hand through everything.

**Comment by nano-shino** [comment]
Found the issue that the .env file wasn't loaded into the environment.
In the shell that you run `python main.py` you should be able to do `echo $BOT_TOKEN` to print it out.
You can set it temporarily with `export BOT_TOKEN=...` if you don't want to use .service.

The error could've been clearer that the bot token is empty.
